---

num_clients: 10 # total number of clients
num_epochs: 2 # number of local epochs
batch_size: 32
num_rounds: 10
clients_per_round: 4
stragglers_fraction: 0.9
learning_rate: 0.03

client_resources:
  num_cpus: 6
  num_gpus: 2.0

server_device: cpu

dataset_config:
  iid: true
  balance: false
  power_law: true
  dataset_name: pathmnist

